[package]
name = "brances"
version = "0.1.0"
authors = ["konstantin.konahevich@uacoders.com <konstantin.konahevich@uacoders.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
